#!/bin/bash
### BEGIN INIT INFO
# Provides:          alarm-controller
# Required-Start:    bluetooth
# Required-Stop:     motion
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

DAEMON=/opt/alarm-controller/bin/alarm-controller
CONFIG=/opt/alarm-controller/etc/alarm-controller.conf

case "$1" in
  start)
  	$DAEMON -a start -f $CONFIG
  	rc=$?
  	;;
  stop)
  	$DAEMON -a stop -f $CONFIG
  	rc=$?
  	;;
  *)
    echo $"Usage: $0 {start|stop}"
    exit 2
esac

exit $rc
